### ISSUE TITLE
Bad font viewing home page comic on Chromium Ubuntu 16.04

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish.github.io#50]
![batfish github io comic-wrong-font](https://user-images.githubusercontent.com/7737874/57873809-056f8200-77c4-11e9-9e6f-9db96e24ec4a.png)

Font may need to be embedded in some way.

**Comment by dhalperi** [comment]
Can't we embed the fonts in the SVG @alb-17la ?

https://graphicdesign.stackexchange.com/questions/73531/illustrator-how-to-embed-fonts-in-svg-file

**Comment by alb-17la** [comment]
We certainly could, but if we really wanted to keep the file as an svg we would trace the letters instead of including the entire font

I went with a high resolution png instead because apart from this issue, I would sometimes notice a slight flicker of individual svg elements loading onto the page which I found annoying.
